using System.Text.Json.Serialization;
using VTubeStudio.Client.Events;
using VTubeStudio.Client.Messages;

namespace VTubeStudio.Client.Serialization;

/// <summary>
/// Source-generated <see cref="JsonSerializerContext"/> for the VTube Studio wire types.
/// Keeps the library AOT- and trim-friendly: no reflection-driven serialisation at runtime.
/// </summary>
[JsonSourceGenerationOptions(
    PropertyNameCaseInsensitive = true,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    GenerationMode = JsonSourceGenerationMode.Default)]
[JsonSerializable(typeof(VTubeStudioEnvelope))]
[JsonSerializable(typeof(ApiErrorData))]
[JsonSerializable(typeof(ApiStateResponse))]
[JsonSerializable(typeof(StatisticsResponse))]
[JsonSerializable(typeof(FaceFoundResponse))]
[JsonSerializable(typeof(VtsFolderInfoResponse))]
[JsonSerializable(typeof(SceneColorOverlayInfoResponse))]
[JsonSerializable(typeof(SceneColorCapturePart))]
// Authentication
[JsonSerializable(typeof(AuthenticationTokenRequest))]
[JsonSerializable(typeof(AuthenticationTokenResponse))]
[JsonSerializable(typeof(AuthenticationRequest))]
[JsonSerializable(typeof(AuthenticationResponse))]
[JsonSerializable(typeof(PermissionRequest))]
[JsonSerializable(typeof(PermissionResponse))]
[JsonSerializable(typeof(PermissionInfo))]
// Models
[JsonSerializable(typeof(CurrentModelResponse))]
[JsonSerializable(typeof(AvailableModelsResponse))]
[JsonSerializable(typeof(AvailableModel))]
[JsonSerializable(typeof(ModelLoadRequest))]
[JsonSerializable(typeof(ModelLoadResponse))]
[JsonSerializable(typeof(MoveModelRequest))]
// Hotkeys + expressions
[JsonSerializable(typeof(HotkeysInCurrentModelRequest))]
[JsonSerializable(typeof(HotkeysInCurrentModelResponse))]
[JsonSerializable(typeof(AvailableHotkey))]
[JsonSerializable(typeof(HotkeyTriggerRequest))]
[JsonSerializable(typeof(HotkeyTriggerResponse))]
[JsonSerializable(typeof(ExpressionStateRequest))]
[JsonSerializable(typeof(ExpressionStateResponse))]
[JsonSerializable(typeof(ExpressionInfo))]
[JsonSerializable(typeof(ExpressionHotkey))]
[JsonSerializable(typeof(ExpressionParameter))]
[JsonSerializable(typeof(ExpressionActivationRequest))]
// Parameters
[JsonSerializable(typeof(InputParameterListResponse))]
[JsonSerializable(typeof(Live2DParameterListResponse))]
[JsonSerializable(typeof(ParameterInfo))]
[JsonSerializable(typeof(ParameterValueRequest))]
[JsonSerializable(typeof(InjectParameterDataRequest))]
[JsonSerializable(typeof(ParameterValue))]
[JsonSerializable(typeof(ParameterCreationRequest))]
[JsonSerializable(typeof(ParameterCreationResponse))]
[JsonSerializable(typeof(ParameterDeletionRequest))]
[JsonSerializable(typeof(ParameterDeletionResponse))]
// ArtMesh
[JsonSerializable(typeof(ArtMeshListResponse))]
[JsonSerializable(typeof(ArtMeshGroup))]
[JsonSerializable(typeof(ColorTintRequest))]
[JsonSerializable(typeof(ColorTintResponse))]
[JsonSerializable(typeof(ColorTint))]
[JsonSerializable(typeof(ArtMeshMatcher))]
[JsonSerializable(typeof(ArtMeshHit))]
[JsonSerializable(typeof(ArtMeshHitInfo))]
[JsonSerializable(typeof(ArtMeshSelectionRequest))]
[JsonSerializable(typeof(ArtMeshSelectionResponse))]
[JsonSerializable(typeof(ArtMeshAtPositionRequest))]
[JsonSerializable(typeof(ArtMeshAtPositionResponse))]
[JsonSerializable(typeof(ArtMeshPosition))]
[JsonSerializable(typeof(ArtMeshWindowSize))]
// Items
[JsonSerializable(typeof(ItemListRequest))]
[JsonSerializable(typeof(ItemListResponse))]
[JsonSerializable(typeof(ItemInstance))]
[JsonSerializable(typeof(AvailableItemFile))]
[JsonSerializable(typeof(ItemLoadRequest))]
[JsonSerializable(typeof(ItemLoadResponse))]
[JsonSerializable(typeof(ItemUnloadRequest))]
[JsonSerializable(typeof(ItemUnloadResponse))]
[JsonSerializable(typeof(UnloadedItem))]
[JsonSerializable(typeof(ItemAnimationControlRequest))]
[JsonSerializable(typeof(ItemAnimationControlResponse))]
[JsonSerializable(typeof(ItemMoveRequest))]
[JsonSerializable(typeof(ItemMoveInstruction))]
[JsonSerializable(typeof(ItemMoveResponse))]
[JsonSerializable(typeof(ItemMoveResult))]
[JsonSerializable(typeof(ItemSortRequest))]
[JsonSerializable(typeof(ItemSortResponse))]
[JsonSerializable(typeof(ItemPinRequest))]
[JsonSerializable(typeof(ItemPinInfo))]
[JsonSerializable(typeof(ItemPinResponse))]
// Physics
[JsonSerializable(typeof(GetCurrentModelPhysicsResponse))]
[JsonSerializable(typeof(PhysicsGroup))]
[JsonSerializable(typeof(SetCurrentModelPhysicsRequest))]
[JsonSerializable(typeof(PhysicsOverride))]
// NDI
[JsonSerializable(typeof(NdiConfigRequest))]
[JsonSerializable(typeof(NdiConfigResponse))]
// Post-processing
[JsonSerializable(typeof(PostProcessingListRequest))]
[JsonSerializable(typeof(PostProcessingListResponse))]
[JsonSerializable(typeof(PostProcessingEffect))]
[JsonSerializable(typeof(PostProcessingEffectConfig))]
[JsonSerializable(typeof(PostProcessingUpdateRequest))]
[JsonSerializable(typeof(PostProcessingValue))]
[JsonSerializable(typeof(PostProcessingUpdateResponse))]
// Events
[JsonSerializable(typeof(EventSubscriptionRequest))]
[JsonSerializable(typeof(EventSubscriptionResponse))]
[JsonSerializable(typeof(TestEventConfig))]
[JsonSerializable(typeof(ModelLoadedEventConfig))]
[JsonSerializable(typeof(ModelOutlineEventConfig))]
[JsonSerializable(typeof(HotkeyTriggeredEventConfig))]
[JsonSerializable(typeof(ModelAnimationEventConfig))]
[JsonSerializable(typeof(ItemEventConfig))]
[JsonSerializable(typeof(ModelClickedEventConfig))]
[JsonSerializable(typeof(ExpressionToggledEventConfig))]
[JsonSerializable(typeof(ArtMeshTrackingEventConfig))]
[JsonSerializable(typeof(ArtMeshTrackingPoint))]
[JsonSerializable(typeof(ArtMeshTrackingCoords))]
[JsonSerializable(typeof(ArtMeshOutlineEventConfig))]
[JsonSerializable(typeof(ArtMeshOutlineEntry))]
[JsonSerializable(typeof(TestEventPayload))]
[JsonSerializable(typeof(ModelOutlineEventPayload))]
[JsonSerializable(typeof(Live2DCubismEditorConnectedEventPayload))]
[JsonSerializable(typeof(ExpressionToggledEventPayload))]
[JsonSerializable(typeof(ArtMeshTrackingEventPayload))]
[JsonSerializable(typeof(TrackedArtMeshPoint))]
[JsonSerializable(typeof(ArtMeshOutlineEventPayload))]
[JsonSerializable(typeof(ArtMeshOutline))]
[JsonSerializable(typeof(ArtMeshOutlineRing))]
[JsonSerializable(typeof(ModelLoadedEventPayload))]
[JsonSerializable(typeof(TrackingStatusChangedEventPayload))]
[JsonSerializable(typeof(BackgroundChangedEventPayload))]
[JsonSerializable(typeof(ModelConfigChangedEventPayload))]
[JsonSerializable(typeof(ModelMovedEventPayload))]
[JsonSerializable(typeof(ModelPosition))]
[JsonSerializable(typeof(HotkeyTriggeredEventPayload))]
[JsonSerializable(typeof(ModelAnimationEventPayload))]
[JsonSerializable(typeof(ItemEventPayload))]
[JsonSerializable(typeof(ModelClickedEventPayload))]
[JsonSerializable(typeof(ClickPosition))]
[JsonSerializable(typeof(WindowSize))]
[JsonSerializable(typeof(PostProcessingEventPayload))]
public sealed partial class VTubeStudioJsonContext : JsonSerializerContext;
